[
{"key": "intro", "navtitle": "הקדמה", "duration": "", "content": "tr-sp-intro.html", "addto": "#special-nav", "disable_comments": true},
{"key": "hodu", "navtitle": "הודו שלך", "duration": "04:19", "content": "tr-hodu.html"},
{"key": "shomea", "navtitle": "מה שאני שומע", "duration": "02:53", "content": "tr-shomea.html"},
{"key": "three-loves", "navtitle": "שלוש אהבות", "duration": "00:39", "content": "tr-three-loves.html"},
{"key": "halev", "navtitle": "הלב שלך אצלו", "duration": "01:58", "content": "tr-halev.html"},
{"key": "optimism", "navtitle": "אופטימיות", "duration": "02:42", "content": "tr-optimism.html"},
{"key": "hayim", "navtitle": "החיים שנגמרו", "duration": "00:25", "content": "tr-hayim.html"},
{"key": "darkness-light", "navtitle": "בין החושך לאור", "duration": "03:58", "content": "tr-darkness-light.html"},
{"key": "shir-ahava", "navtitle": "שיר אהבה מזמן רע", "duration": "03:32", "content": "tr-shir-ahava.html"},
{"key": "shir-taltalim", "navtitle": "שיר תלתלים", "duration": "04:07", "content": "tr-shir-taltalim.html"},
{"key": "zikaron-atzmaut", "navtitle": "יום הזיכרון יום העצמאות", "duration": "01:10", "content": "tr-zikaron-atzmaut.html"},
{"key": "buba-memukenet", "navtitle": "בובה ממוכנת", "duration": "03:00", "content": "tr-buba-memukenet.html"},
{"key": "dream-woman", "navtitle": "האישה מהחלומות", "duration": "02:33", "content": "tr-dream-woman.html"},
{"key": "levad", "navtitle": "רוצה לבד", "duration": "03:14", "content": "tr-levad.html"},
{"key": "hadikaon", "navtitle": "הדיכאון", "duration": "02:51", "content": "tr-hadikaon.html"},
{"key": "lehaverti", "navtitle": "לחברתי", "duration": "00:27", "content": "tr-lehaverti.html"},
{"key": "lamdeni", "navtitle": "למדני אלהי", "duration": "02:29", "content": "tr-lamdeni.html"},
{"key": "burgul", "navtitle": "Burgul Abu Burgul", "duration": "04:14", "content": "tr-burgul.html"},
{"key": "tzorahat", "navtitle": "צורחת", "duration": "04:03", "content": "tr-tzorahat.html"},
{"key": "yadayim", "navtitle": "קחי את עצמך בידיים", "duration": "00:43", "content": "tr-yadayim.html"},
{"key": "sagol", "navtitle": "עוטף עצמי בסגול", "duration": "01:49", "content": "tr-sagol.html"},
{"key": "no-such-love", "navtitle": "אחרי אהבה כזו", "duration": "03:39", "content": "tr-no-such-love.html"},
{"key": "teatron", "navtitle": "תיאטרון", "duration": "02:56", "content": "tr-teatron.html"},
{"key": "ashlayot", "navtitle": "סמטת האשליות", "duration": "00:24", "content": "tr-ashlayot.html"},
{"key": "paam", "navtitle": "פעם, בחיים", "duration": "03:53", "content": "tr-paam.html"},
{"key": "shemesh", "navtitle": "שמש בלבך", "duration": "01:27", "content": "tr-shemesh.html"},
{"key": "prachim", "navtitle": "פרחים", "duration": "03:40", "content": "tr-prachim.html"},
{"key": "hadikaon-bonus", "navtitle": "הדיכאון (בונוס)", "duration": "03:02", "content": "tr-hadikaon-bonus.html"},
{"key": "michtav", "navtitle": "מכתב לדרך", "duration": "02:35", "content": "tr-michtav.html"}
]